services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./.env
    ports:
      - "6000:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
  redisDB:
